/**
 * frics-coin.js — the FRICS™ coin renderer (one implementation, reused).
 *
 *   FRICSCoin.create(canvas, { size, shadow }) → coin
 *     coin.pose = { ry, rx, rz }      radians; call coin.render() after changing it
 *     coin.ready(cb)                  fires once textures + scene exist (immediately if already so)
 *     coin.resize()                   re-fit to the canvas CSS size
 *     coin.dispose()
 *
 * Built on the three.js r158 build the homepage globe already loads — no new library.
 * Geometry: raised rim (lathe), recessed field faces, lettered reeded edge. Materials: PBR metal with
 * relief normal maps + roughness/metalness maps generated by frics-art.js (memoised, so a second coin
 * shares the build) and a small procedural studio environment (PMREM). Without WebGL it falls back
 * to the flat sprite with a turn. The showcase controller below (CXStory 'fricscoin') runs the four
 * credit stages — available · acquired · allocated · impact monitored — and only renders while on screen.
 */
(function () {
  'use strict';
  if (window.FRICSCoin) return;

  var THREE = window.THREE, Art = window.FRICSArt;

  function hasWebGL() {
    try { var c = document.createElement('canvas'); return !!(c.getContext('webgl2') || c.getContext('webgl')); } catch (e) { return false; }
  }

  /* studio: broad front softbox (what a face-on coin reflects), key, cool strip, faint warm accent */
  function envTexture() {
    var c = document.createElement('canvas'); c.width = 1024; c.height = 512;
    var g = c.getContext('2d'), gr = g.createLinearGradient(0, 0, 0, 512);
    gr.addColorStop(0, '#7f93b8'); gr.addColorStop(0.5, '#2a3b5e'); gr.addColorStop(1, '#0a101c');
    g.fillStyle = gr; g.fillRect(0, 0, 1024, 512);
    g.shadowColor = '#dfe9fa'; g.shadowBlur = 90; g.fillStyle = 'rgba(214,226,246,0.78)'; g.fillRect(610, 120, 320, 250);
    g.shadowBlur = 40; g.shadowColor = '#fff'; g.fillStyle = 'rgba(255,255,255,0.97)'; g.fillRect(150, 70, 230, 110);
    g.shadowColor = '#9cc6ff'; g.fillStyle = 'rgba(160,200,255,0.9)'; g.fillRect(500, 110, 60, 260);
    g.shadowColor = '#e9a56b'; g.fillStyle = 'rgba(232,150,90,0.6)'; g.fillRect(950, 200, 60, 50);
    g.shadowColor = '#fff'; g.fillStyle = 'rgba(255,255,255,0.6)'; g.fillRect(400, 20, 180, 30);
    var t = new THREE.CanvasTexture(c); t.mapping = THREE.EquirectangularReflectionMapping; t.colorSpace = THREE.SRGBColorSpace;
    return t;
  }

  function shadowTexture() {
    var c = document.createElement('canvas'); c.width = c.height = 256;
    var g = c.getContext('2d'), gr = g.createRadialGradient(128, 128, 0, 128, 128, 128);
    gr.addColorStop(0, 'rgba(0,0,0,0.55)'); gr.addColorStop(0.6, 'rgba(0,0,0,0.16)'); gr.addColorStop(1, 'rgba(0,0,0,0)');
    g.fillStyle = gr; g.fillRect(0, 0, 256, 256);
    return new THREE.CanvasTexture(c);
  }

  function tex(canvas, color, aniso) {
    var t = new THREE.CanvasTexture(canvas);
    if (color) t.colorSpace = THREE.SRGBColorSpace;
    t.anisotropy = aniso; t.generateMipmaps = true; t.minFilter = THREE.LinearMipmapLinearFilter;
    return t;
  }

  function create(canvas, opts) {
    opts = opts || {};
    var coin = { pose: { ry: 0.55, rx: 0, rz: 0 }, isReady: false, flat: false, dpr: 1 };
    var waiting = [], R = null, dead = false;

    function dpr() { return Math.min(window.devicePixelRatio || 1, opts.dprCap || 2.5); }

    function build(front, back) {
      var r = new THREE.WebGLRenderer({ canvas: canvas, antialias: true, alpha: true, powerPreference: 'high-performance' });
      r.outputColorSpace = THREE.SRGBColorSpace; r.toneMapping = THREE.ACESFilmicToneMapping; r.toneMappingExposure = 1.0;
      r.setClearColor(0x000000, 0);
      var scene = new THREE.Scene(), cam = new THREE.PerspectiveCamera(26, 1, 0.1, 30);
      var pm = new THREE.PMREMGenerator(r), et = envTexture();
      scene.environment = pm.fromEquirectangular(et).texture; et.dispose(); pm.dispose();
      var aniso = Math.min(8, r.capabilities.getMaxAnisotropy()), pivot = new THREE.Group(); scene.add(pivot);
      var metal = new THREE.MeshStandardMaterial({ color: 0xBDC8DA, metalness: 1, roughness: 0.28, envMapIntensity: 1.4, side: THREE.DoubleSide });
      [1, -1].forEach(function (s) {
        var pts = [[0.865, 0.055], [0.872, 0.072], [0.885, 0.078], [0.965, 0.078], [0.99, 0.07], [1.0, 0.055]].map(function (p) { return new THREE.Vector2(p[0], p[1] * s); });
        var g = new THREE.LatheGeometry(pts, 192); g.rotateX(Math.PI / 2); pivot.add(new THREE.Mesh(g, metal));
      });
      var en = tex(Art.buildEdge().normal, false, aniso); en.wrapS = THREE.RepeatWrapping;
      var eg = new THREE.CylinderGeometry(1, 1, 0.11, 256, 1, true); eg.rotateX(Math.PI / 2);
      pivot.add(new THREE.Mesh(eg, new THREE.MeshStandardMaterial({ color: 0xB4C0D2, metalness: 1, roughness: 0.32, envMapIntensity: 1.6, normalMap: en, normalScale: new THREE.Vector2(1.4, 1.4) })));
      function face(set, z, flip) {
        var m = new THREE.MeshStandardMaterial({ map: tex(set.albedo, true, aniso), normalMap: tex(set.normal, false, aniso), roughnessMap: tex(set.orm, false, aniso), metalness: 1, roughness: 1, envMapIntensity: 1.6, normalScale: new THREE.Vector2(1.6, 1.6) });
        m.metalnessMap = m.roughnessMap;
        var mesh = new THREE.Mesh(new THREE.CircleGeometry(0.87, 160), m); mesh.position.z = z; if (flip) mesh.rotation.y = Math.PI; pivot.add(mesh);
      }
      face(front, 0.055, false); face(back, -0.055, true);
      var key = new THREE.DirectionalLight(0xffffff, 1.15); key.position.set(-2.2, 3, 4); scene.add(key);
      var fill = new THREE.DirectionalLight(0x6fa8f5, 0.55); fill.position.set(3, -1, 2); scene.add(fill);
      var sh = null;
      if (opts.shadow !== false) {
        sh = new THREE.Mesh(new THREE.PlaneGeometry(2.6, 0.7), new THREE.MeshBasicMaterial({ map: shadowTexture(), transparent: true, depthWrite: false, opacity: 0.8 }));
        sh.rotation.x = -Math.PI / 2; sh.position.y = -1.28; scene.add(sh);
      }
      R = { r: r, scene: scene, cam: cam, pivot: pivot, shadow: sh };
    }

    coin.resize = function () {
      var w = canvas.clientWidth, h = canvas.clientHeight;
      if (!w || !h) return;
      if (R) {
        R.r.setPixelRatio(dpr()); R.r.setSize(w, h, false); R.cam.aspect = w / h;
        var fov = R.cam.fov * Math.PI / 180, need = opts.shadow === false ? 2.3 : 2.55;
        var dH = need / 2 / Math.tan(fov / 2), dW = need / 2 / (Math.tan(fov / 2) * R.cam.aspect);
        R.cam.position.set(0, opts.shadow === false ? 0.12 : 0.35, Math.max(dH, dW) * 1.02); R.cam.lookAt(0, opts.shadow === false ? 0 : -0.05, 0); R.cam.updateProjectionMatrix();
      } else if (coin.flat) { coin.dpr = dpr(); canvas.width = w * coin.dpr; canvas.height = h * coin.dpr; }
      if (coin.isReady) coin.render();
    };

    coin.render = function () {
      var p = coin.pose;
      if (R) {
        R.pivot.rotation.set(-0.09 + p.rx + Math.sin(p.ry * 0.7) * 0.03, p.ry, p.rz);
        if (R.shadow) R.shadow.scale.set(0.6 + 0.4 * Math.abs(Math.cos(p.ry)), 1, 1);
        R.r.render(R.scene, R.cam);
      } else if (coin.flat && Art) {
        var w = canvas.clientWidth, h = canvas.clientHeight, d = coin.dpr, s = Math.min(w, h) * 0.86, c = Math.cos(p.ry);
        var g = canvas.getContext('2d'); g.setTransform(d, 0, 0, d, 0, 0); g.clearRect(0, 0, w, h);
        var sp = Art.sprite(c >= 0 ? 'front' : 'back', Math.round(s * d)), ww = Math.max(2, Math.abs(c) * s);
        g.drawImage(sp, (w - ww) / 2, (h - s) / 2, ww, s);
      }
    };

    coin.ready = function (cb) { if (coin.isReady) cb(coin); else waiting.push(cb); };
    function done() { coin.isReady = true; coin.resize(); waiting.splice(0).forEach(function (f) { f(coin); }); }

    coin.dispose = function () {
      dead = true;
      if (R) { R.r.dispose(); if (R.r.forceContextLoss) R.r.forceContextLoss(); R = null; }
    };

    /* start building soon, but never wait on a busy main thread (idle callbacks can be starved by other render loops) */
    (window.requestIdleCallback ? function (f) { window.requestIdleCallback(f, { timeout: 600 }); } : function (f) { setTimeout(f, 150); })(function () {
      if (dead) return;
      if (!Art || !THREE || !hasWebGL()) { coin.flat = true; (Art ? Art.loadLogo() : Promise.resolve()).then(done); return; }
      var S = opts.size || 1536;
      Art.faces(S).then(function (f) {
        if (dead) return;
        try { build(f.front, f.back); } catch (e) { console.warn('[FRICS coin] WebGL init failed', e); coin.flat = true; }
        done();
      });
    });
    return coin;
  }

  window.FRICSCoin = { create: create };

  /* ── Showcase: the same coin through its four states ── */
  var STATES = [
    { k: 'available', tag: 'Stage 02', status: 'Available', line: 'Inventory is open for acquisition at the project price.', ry: 0.55 },
    { k: 'acquired',  tag: 'Stage 03', status: 'Acquired',  line: 'An eligible company acquires FRICS and becomes the holder of record.', ry: 2.55 },
    { k: 'allocated', tag: 'Stage 04', status: 'Allocated', line: 'The acquisition is allocated to the resilience project it funds.', ry: 4.35 },
    { k: 'monitored', tag: 'Stage 06', status: 'Impact monitored', line: 'Project indicators are measured and reported against a baseline.', ry: 6.83 }
  ];

  function showcase(root) {
    var stage = root.querySelector('.frx-coinstage'), canvas = stage.querySelector('canvas');
    var chips = [].slice.call(root.querySelectorAll('[data-state]')), statusEl = root.querySelector('[data-status]'), lineEl = root.querySelector('[data-state-line]');
    var tier = CXStory.tier();
    var coin = FRICSCoin.create(canvas, { size: (tier === 'mobile' || CXStory.saveData()) ? 1024 : ((window.devicePixelRatio || 1) >= 2 && tier === 'desktop' ? 2048 : 1536) });
    var st = { visible: false, run: false, raf: 0, t0: 0, spin: 0.55, target: 0.55, state: -1, auto: true, timer: 0, px: 0, py: 0, tx: 0, ty: 0, still: false };

    function setState(i) {
      if (st.state === i) return;
      st.state = i; st.target = STATES[i].ry;
      chips.forEach(function (c, k) { c.classList.toggle('is-on', k === i); c.setAttribute('aria-pressed', k === i ? 'true' : 'false'); });
      if (statusEl) statusEl.textContent = STATES[i].status;
      if (lineEl) lineEl.textContent = STATES[i].line;
      stage.setAttribute('data-state-now', STATES[i].k);
      if (st.still) { st.spin = st.target; coin.pose.ry = st.spin; coin.render(); }
      kick();
    }

    function loop(now) {
      st.raf = 0;
      if (!st.run || !st.visible || st.still) return;
      var dt = Math.min(0.05, (now - st.t0) / 1000); st.t0 = now;
      st.spin += (st.target - st.spin) * Math.min(1, dt * 2.6) + dt * 0.10;         // ease to the state's pose, plus a slow drift
      st.target += dt * 0.10;
      st.tx += (st.px - st.tx) * 0.06; st.ty += (st.py - st.ty) * 0.06;
      coin.pose.ry = st.spin; coin.pose.rx = st.ty * 0.14; coin.pose.rz = st.tx * 0.04;
      coin.render();
      st.raf = requestAnimationFrame(loop);
    }
    function kick() { if (!st.raf && st.run && st.visible && !st.still && coin.isReady) { st.t0 = performance.now(); st.raf = requestAnimationFrame(loop); } }
    function cycle() { clearInterval(st.timer); st.timer = setInterval(function () { if (st.auto && st.visible) setState((st.state + 1) % STATES.length); }, 4200); }

    chips.forEach(function (c, i) { c.addEventListener('click', function () { st.auto = false; setState(i); }); });
    var ro = window.ResizeObserver ? new ResizeObserver(function () { coin.resize(); }) : null;
    if (ro) ro.observe(canvas);
    var un = CXStory.watchVisible(root, function (v) { st.visible = v; if (v) kick(); });
    if (tier === 'desktop' && !CXStory.reducedMotion()) {
      stage.addEventListener('pointermove', function (e) { var b = stage.getBoundingClientRect(); st.px = ((e.clientX - b.left) / b.width - 0.5) * 2; st.py = ((e.clientY - b.top) / b.height - 0.5) * 2; }, { passive: true });
      stage.addEventListener('pointerleave', function () { st.px = st.py = 0; });
    }
    coin.ready(function () { stage.classList.add('is-ready'); if (coin.flat) stage.classList.add('is-flat'); coin.pose.ry = st.spin; coin.render(); kick(); });
    setState(0);

    return {
      play: function () { st.run = true; cycle(); kick(); },
      replay: function () { st.run = true; kick(); },
      showFinal: function () { st.still = true; st.auto = false; setState(0); coin.ready(function () { coin.pose.ry = STATES[0].ry; coin.render(); }); },
      seek: function (a) { coin.pose.ry = a; coin.render(); },
      destroy: function () { cancelAnimationFrame(st.raf); clearInterval(st.timer); un(); if (ro) ro.disconnect(); coin.dispose(); }
    };
  }

  function reg() { if (window.CXStory) CXStory.register('fricscoin', showcase); else setTimeout(reg, 30); }
  reg();
})();
