"use client";

import { useEffect, useState } from "react";
import { FileDown } from "lucide-react";
import Card from "@/components/ds/Card";
import Button from "@/components/ds/Button";
import EmptyState from "@/components/ds/EmptyState";
import Table, { type DataTableColumn } from "@/components/ds/Table";
import PageHeader from "@/components/scenario-studio/PageHeader";
import ScenarioSelector from "@/components/scenario-studio/ScenarioSelector";
import { useScenarioRun } from "@/hooks/useScenarioRun";
import { fetchReports, logReport } from "@/lib/api/scenarioStudio";
import { generateScenarioStudioReport } from "@/lib/report-generator/generateScenarioStudioReport";
import type { ScenarioStudioReport } from "@/types/scenario-studio";

export default function ReportsPage() {
  const { company, run, loading, error } = useScenarioRun();
  const [reports, setReports] = useState<ScenarioStudioReport[]>([]);
  const [generating, setGenerating] = useState(false);

  function load() {
    fetchReports().then(setReports);
  }

  useEffect(load, []);

  async function handleGenerate() {
    if (!company || !run) return;
    setGenerating(true);
    try {
      await generateScenarioStudioReport(company, run);
      await logReport({ companyId: company.id, companyName: company.name, scenario: run.scenario, year: run.year });
      load();
    } finally {
      setGenerating(false);
    }
  }

  const columns: DataTableColumn<ScenarioStudioReport>[] = [
    { key: "company", header: "Company", accessor: (r) => r.companyName },
    { key: "scenario", header: "Scenario", accessor: (r) => r.scenario },
    { key: "year", header: "Horizon", accessor: (r) => String(r.year) },
    { key: "generatedAt", header: "Generated", accessor: (r) => new Date(r.generatedAt).toLocaleString() },
    { key: "generatedBy", header: "Generated by", accessor: (r) => r.generatedBy },
  ];

  return (
    <div>
      <PageHeader
        title="Reports"
        description="Institutional-quality PDF reports — executive summary, asset-level risk, methodology, and full audit trail."
        action={
          <Button size="sm" onClick={handleGenerate} disabled={!run || generating}>
            <FileDown size={14} /> {generating ? "Generating…" : "Generate report"}
          </Button>
        }
      />

      <div className="mb-4">
        <ScenarioSelector showCompareToggle={false} />
      </div>

      {loading && <p className="font-ds-body text-[13px] text-ds-muted">Loading…</p>}
      {!loading && error && <p className="mb-4 font-ds-body text-[13px] text-ds-warning">{error}</p>}

      <Card title="Report history">
        {reports.length === 0 ? (
          <EmptyState title="No reports yet" description="Generate your first report from the current simulation above." />
        ) : (
          <Table columns={columns} data={reports} getRowId={(r) => r.id} exportFilename="scenario-studio-reports" />
        )}
      </Card>
    </div>
  );
}
