import type { SectorConfig, Industry } from "@/types";

export const SECTOR_CONFIGS: Record<Industry, SectorConfig> = {
  "energy-oil-gas": {
    id: "energy-oil-gas",
    label: "Energy — Oil & Gas",
    carbonIntensityBenchmark: 520,
    waterStressSensitivity: 0.65,
    regulatoryExposure: 0.95,
    supplyChainVulnerability: 0.80,
    physicalAssetRisk: 0.75,
    subSectors: ["Upstream E&P", "Midstream", "Downstream", "Integrated"],
    tcfdRequirements: [
      "Stranded asset analysis",
      "Carbon budget alignment",
      "Methane intensity disclosure",
      "Flaring reduction targets",
    ],
  },
  "energy-utilities": {
    id: "energy-utilities",
    label: "Energy — Utilities",
    carbonIntensityBenchmark: 380,
    waterStressSensitivity: 0.80,
    regulatoryExposure: 0.90,
    supplyChainVulnerability: 0.55,
    physicalAssetRisk: 0.70,
    subSectors: ["Electric Power", "Gas Distribution", "Water Utilities"],
    tcfdRequirements: [
      "Grid resilience assessment",
      "Renewable transition plan",
      "Water usage intensity",
      "Capacity factor projections",
    ],
  },
  "energy-renewables": {
    id: "energy-renewables",
    label: "Energy — Renewables",
    carbonIntensityBenchmark: 25,
    waterStressSensitivity: 0.40,
    regulatoryExposure: 0.30,
    supplyChainVulnerability: 0.60,
    physicalAssetRisk: 0.55,
    subSectors: ["Solar", "Wind", "Hydro", "Geothermal", "Bioenergy"],
    tcfdRequirements: [
      "Resource variability assessment",
      "Physical site risk",
      "Supply chain minerals",
    ],
  },
  "manufacturing-heavy": {
    id: "manufacturing-heavy",
    label: "Manufacturing — Heavy Industry",
    carbonIntensityBenchmark: 450,
    waterStressSensitivity: 0.70,
    regulatoryExposure: 0.85,
    supplyChainVulnerability: 0.75,
    physicalAssetRisk: 0.65,
    subSectors: ["Steel", "Aluminum", "Industrial Machinery", "Shipbuilding"],
    tcfdRequirements: [
      "Process emissions disclosure",
      "Energy efficiency roadmap",
      "Carbon pricing exposure",
    ],
  },
  "manufacturing-chemicals": {
    id: "manufacturing-chemicals",
    label: "Manufacturing — Chemicals",
    carbonIntensityBenchmark: 490,
    waterStressSensitivity: 0.75,
    regulatoryExposure: 0.88,
    supplyChainVulnerability: 0.80,
    physicalAssetRisk: 0.60,
    subSectors: ["Specialty Chemicals", "Petrochemicals", "Fertilizers", "Plastics"],
    tcfdRequirements: [
      "Chemical risk disclosure",
      "Water contamination risk",
      "Feedstock transition plan",
    ],
  },
  "manufacturing-cement": {
    id: "manufacturing-cement",
    label: "Manufacturing — Cement",
    carbonIntensityBenchmark: 580,
    waterStressSensitivity: 0.60,
    regulatoryExposure: 0.82,
    supplyChainVulnerability: 0.50,
    physicalAssetRisk: 0.55,
    subSectors: ["Portland Cement", "Ready-Mix Concrete", "Aggregates"],
    tcfdRequirements: [
      "Clinker ratio targets",
      "Alternative fuel mix",
      "Carbon capture readiness",
    ],
  },
  "agriculture-food": {
    id: "agriculture-food",
    label: "Agriculture & Food",
    carbonIntensityBenchmark: 290,
    waterStressSensitivity: 0.95,
    regulatoryExposure: 0.65,
    supplyChainVulnerability: 0.90,
    physicalAssetRisk: 0.85,
    subSectors: ["Crop Production", "Livestock", "Food Processing", "Aquaculture"],
    tcfdRequirements: [
      "Water usage intensity",
      "Land use change",
      "Supply chain deforestation",
      "Yield risk under warming",
    ],
  },
  "real-estate": {
    id: "real-estate",
    label: "Real Estate & Construction",
    carbonIntensityBenchmark: 180,
    waterStressSensitivity: 0.55,
    regulatoryExposure: 0.70,
    supplyChainVulnerability: 0.65,
    physicalAssetRisk: 0.90,
    subSectors: ["Commercial", "Residential", "Industrial", "Infrastructure"],
    tcfdRequirements: [
      "Flood zone exposure",
      "Energy efficiency ratings",
      "Building code resilience",
      "Coastal asset risk",
    ],
  },
  "transportation": {
    id: "transportation",
    label: "Transportation & Logistics",
    carbonIntensityBenchmark: 320,
    waterStressSensitivity: 0.35,
    regulatoryExposure: 0.80,
    supplyChainVulnerability: 0.70,
    physicalAssetRisk: 0.60,
    subSectors: ["Shipping", "Aviation", "Road Freight", "Rail", "Ports"],
    tcfdRequirements: [
      "Fleet electrification plan",
      "Route vulnerability",
      "IMO 2050 alignment",
      "Infrastructure resilience",
    ],
  },
  "financial-services": {
    id: "financial-services",
    label: "Financial Services & Insurance",
    carbonIntensityBenchmark: 45,
    waterStressSensitivity: 0.20,
    regulatoryExposure: 0.75,
    supplyChainVulnerability: 0.50,
    physicalAssetRisk: 0.40,
    subSectors: ["Banking", "Insurance", "Asset Management", "Private Equity"],
    tcfdRequirements: [
      "Financed emissions (PCAF)",
      "Portfolio alignment",
      "Physical risk of loan book",
      "Stress testing",
    ],
  },
  "technology": {
    id: "technology",
    label: "Technology & Data Centers",
    carbonIntensityBenchmark: 85,
    waterStressSensitivity: 0.65,
    regulatoryExposure: 0.50,
    supplyChainVulnerability: 0.75,
    physicalAssetRisk: 0.45,
    subSectors: ["Cloud/Data Centers", "Hardware", "Software", "Semiconductors"],
    tcfdRequirements: [
      "PUE and WUE disclosure",
      "Renewable energy procurement",
      "Supply chain minerals",
      "Scope 3 hardware emissions",
    ],
  },
  "mining-metals": {
    id: "mining-metals",
    label: "Mining & Metals",
    carbonIntensityBenchmark: 510,
    waterStressSensitivity: 0.85,
    regulatoryExposure: 0.88,
    supplyChainVulnerability: 0.60,
    physicalAssetRisk: 0.80,
    subSectors: ["Coal", "Iron Ore", "Copper", "Lithium", "Gold", "Phosphates"],
    tcfdRequirements: [
      "Mine site flood risk",
      "Tailings dam safety",
      "Water intensity",
      "Just transition plan",
    ],
  },
  "retail-consumer": {
    id: "retail-consumer",
    label: "Retail & Consumer Goods",
    carbonIntensityBenchmark: 120,
    waterStressSensitivity: 0.50,
    regulatoryExposure: 0.55,
    supplyChainVulnerability: 0.85,
    physicalAssetRisk: 0.40,
    subSectors: ["E-commerce", "Apparel", "Food & Beverage", "Electronics"],
    tcfdRequirements: [
      "Supply chain emissions",
      "Consumer product lifecycle",
      "Packaging targets",
    ],
  },
  "healthcare": {
    id: "healthcare",
    label: "Healthcare",
    carbonIntensityBenchmark: 160,
    waterStressSensitivity: 0.45,
    regulatoryExposure: 0.60,
    supplyChainVulnerability: 0.70,
    physicalAssetRisk: 0.50,
    subSectors: ["Hospitals", "Pharmaceuticals", "Medical Devices", "Biotech"],
    tcfdRequirements: [
      "Supply chain resilience",
      "Facility energy use",
      "Cold chain emissions",
    ],
  },
  "water-waste": {
    id: "water-waste",
    label: "Water & Waste Management",
    carbonIntensityBenchmark: 200,
    waterStressSensitivity: 1.0,
    regulatoryExposure: 0.75,
    supplyChainVulnerability: 0.45,
    physicalAssetRisk: 0.75,
    subSectors: ["Water Treatment", "Wastewater", "Solid Waste", "Recycling"],
    tcfdRequirements: [
      "Service area water risk",
      "Flood resilience",
      "Methane capture",
    ],
  },
  "tourism-hospitality": {
    id: "tourism-hospitality",
    label: "Tourism & Hospitality",
    carbonIntensityBenchmark: 140,
    waterStressSensitivity: 0.60,
    regulatoryExposure: 0.45,
    supplyChainVulnerability: 0.55,
    physicalAssetRisk: 0.70,
    subSectors: ["Hotels", "Airlines", "Cruise", "Theme Parks", "Eco-tourism"],
    tcfdRequirements: [
      "Destination risk assessment",
      "Coastal asset exposure",
      "Aviation transition plan",
    ],
  },
};

export const WARMING_SCENARIOS = {
  "1.5": { label: "1.5°C (RCP 2.6)", rcp: "RCP 2.6", color: "#2D6A4F" },
  "2.0": { label: "2°C (RCP 4.5)", rcp: "RCP 4.5", color: "#F4A261" },
  "3.0": { label: "3°C (RCP 6.0)", rcp: "RCP 6.0", color: "#E07B3A" },
  "4.0": { label: "4°C (RCP 8.5)", rcp: "RCP 8.5", color: "#C1121F" },
};

export const CARBON_PRICE_SCENARIOS = {
  current: 50,
  moderate: 75,
  ambitious: 150,
  net_zero: 200,
};
