import type { ReportConfig } from "@/types";
import { generateReportId, formatDate, getRiskColor } from "@/lib/utils";
import { SECTOR_CONFIGS, WARMING_SCENARIOS, CARBON_PRICE_SCENARIOS } from "@/lib/scoring/sectorConfig";

const BRAND = {
  teal: [13, 92, 99] as [number, number, number],
  amber: [244, 162, 97] as [number, number, number],
  danger: [193, 18, 31] as [number, number, number],
  success: [45, 106, 79] as [number, number, number],
  navy: [26, 35, 50] as [number, number, number],
  bg: [240, 247, 244] as [number, number, number],
};

function hex(arr: [number, number, number]) {
  return arr.map((v) => v / 255);
}

export async function generateClimateReport(config: ReportConfig): Promise<void> {
  const { jsPDF } = await import("jspdf");
  await import("jspdf-autotable");

  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const reportId = generateReportId();
  const W = 210;
  const H = 297;
  const M = 18;

  const sector = SECTOR_CONFIGS[config.formData.companyProfile.industry];
  const scenario = WARMING_SCENARIOS[config.formData.scenario.warmingScenario];

  // Helper functions
  function setNavy() { doc.setTextColor(...hex(BRAND.navy).map((v) => v * 255) as [number, number, number]); }
  function setTeal() { doc.setTextColor(...hex(BRAND.teal).map((v) => v * 255) as [number, number, number]); }
  function setGray() { doc.setTextColor(120, 120, 120); }
  function setWhite() { doc.setTextColor(255, 255, 255); }

  function addHeader(title: string, subtitle: string) {
    doc.setFillColor(...BRAND.navy);
    doc.rect(0, 0, W, 12, "F");
    doc.setFillColor(...BRAND.teal);
    doc.rect(0, 12, 4, H - 12, "F");
    setWhite();
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.text("Climactix Global | Climate Risk Intelligence Platform", M, 8);
    doc.text(`Report ID: ${reportId}`, W - M, 8, { align: "right" });

    setNavy();
    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.text(title, M + 6, 26);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    setGray();
    doc.text(subtitle, M + 6, 33);

    doc.setDrawColor(...BRAND.teal);
    doc.setLineWidth(0.5);
    doc.line(M + 6, 37, W - M, 37);
  }

  function addFooter(pageNum: number) {
    doc.setFillColor(245, 245, 245);
    doc.rect(0, H - 10, W, 10, "F");
    doc.setFontSize(7);
    setGray();
    doc.setFont("helvetica", "normal");
    doc.text("Confidential | Generated by Climactix Global | climactix.global", W / 2, H - 4, { align: "center" });
    doc.text(`Page ${pageNum}`, W - M, H - 4, { align: "right" });
    doc.text(formatDate(), M, H - 4);
  }

  function riskBadge(x: number, y: number, rating: string, w = 36) {
    const colors: Record<string, [number, number, number]> = {
      CRITICAL: BRAND.danger,
      HIGH: [224, 123, 58],
      MEDIUM: [244, 162, 97],
      LOW: BRAND.success,
      MINIMAL: BRAND.teal,
    };
    const color = colors[rating] ?? BRAND.teal;
    doc.setFillColor(...color);
    doc.roundedRect(x, y, w, 8, 2, 2, "F");
    setWhite();
    doc.setFontSize(8);
    doc.setFont("helvetica", "bold");
    doc.text(rating, x + w / 2, y + 5.5, { align: "center" });
    setNavy();
    doc.setFont("helvetica", "normal");
  }

  function scoreBar(x: number, y: number, score: number, width: number, label: string) {
    const colors = [
      [45, 106, 79], [244, 162, 97], [224, 123, 58], [193, 18, 31],
    ];
    const colorIndex = score >= 75 ? 3 : score >= 50 ? 2 : score >= 25 ? 1 : 0;
    doc.setFillColor(230, 230, 230);
    doc.roundedRect(x, y, width, 5, 1, 1, "F");
    doc.setFillColor(...colors[colorIndex] as [number, number, number]);
    doc.roundedRect(x, y, (score / 100) * width, 5, 1, 1, "F");
    doc.setFontSize(8);
    setGray();
    doc.text(label, x, y - 2);
    setNavy();
    doc.text(`${score}`, x + width + 2, y + 4);
  }

  // ─── PAGE 1: COVER ───
  doc.setFillColor(...BRAND.navy);
  doc.rect(0, 0, W, H, "F");

  doc.setFillColor(...BRAND.teal);
  doc.rect(0, H * 0.55, W, H * 0.45, "F");

  // Globe SVG text representation
  doc.setFillColor(255, 255, 255);
  doc.circle(W / 2, 55, 18, "F");
  doc.setFillColor(...BRAND.teal);
  doc.circle(W / 2, 55, 14, "F");
  doc.setFillColor(255, 255, 255);
  doc.circle(W / 2, 55, 8, "F");

  setWhite();
  doc.setFontSize(28);
  doc.setFont("helvetica", "bold");
  doc.text("CLIMACTIX GLOBAL", W / 2, 90, { align: "center" });
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text("Climate Risk Intelligence Platform", W / 2, 99, { align: "center" });

  doc.setFillColor(255, 255, 255, 0.2);
  doc.roundedRect(M, 115, W - M * 2, 1, 0, 0, "F");

  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  setWhite();
  doc.text("CLIMATE RISK ASSESSMENT", W / 2, 135, { align: "center" });
  doc.setFontSize(14);
  doc.text("REPORT", W / 2, 145, { align: "center" });

  doc.setFontSize(22);
  doc.setFillColor(...BRAND.amber);
  doc.roundedRect(M, 155, W - M * 2, 18, 3, 3, "F");
  setNavy();
  doc.setFont("helvetica", "bold");
  doc.text(config.companyName || "Organization Assessment", W / 2, 167, { align: "center" });

  doc.setFontSize(10);
  setWhite();
  doc.setFont("helvetica", "normal");
  const meta = [
    ["Sector", config.sector],
    ["Date", config.date],
    ["Time Horizon", `${config.horizon}`],
    ["Warming Scenario", `${config.scenario}°C (${WARMING_SCENARIOS[config.scenario as keyof typeof WARMING_SCENARIOS]?.rcp ?? "RCP 4.5"})`],
    ["Report Type", config.reportType.toUpperCase()],
    ["Report ID", reportId],
  ];
  let metaY = 192;
  meta.forEach(([k, v]) => {
    doc.setFont("helvetica", "normal");
    doc.text(k + ":", M + 6, metaY);
    doc.setFont("helvetica", "bold");
    doc.text(v, 90, metaY);
    metaY += 8;
  });

  doc.setFillColor(0, 0, 0, 0.3);
  doc.setFontSize(8);
  setWhite();
  doc.text("TCFD-ALIGNED DISCLOSURE", M + 6, H - 18);
  doc.text("IPCC AR6 METHODOLOGY", M + 6 + 55, H - 18);
  doc.text("PARIS AGREEMENT ALIGNED", M + 6 + 110, H - 18);

  addFooter(1);

  // ─── PAGE 2: EXECUTIVE SUMMARY ───
  doc.addPage();
  addHeader("Executive Summary", `${config.companyName} · ${config.sector} · Scenario: ${config.scenario}°C warming`);

  let y = 46;

  // Risk rating box
  doc.setFillColor(...BRAND.bg);
  doc.roundedRect(M + 6, y, W - M * 2 - 6, 28, 4, 4, "F");
  doc.setFillColor(...BRAND.teal);
  doc.roundedRect(M + 6, y, 4, 28, 2, 2, "F");

  const riskColors: Record<string, [number, number, number]> = {
    CRITICAL: BRAND.danger, HIGH: [224, 123, 58], MEDIUM: [244, 162, 97], LOW: BRAND.success, MINIMAL: BRAND.teal,
  };
  doc.setFillColor(...(riskColors[config.riskScore.riskRating] ?? BRAND.teal));
  doc.circle(M + 20, y + 14, 10, "F");
  setWhite();
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text(`${config.riskScore.overall}`, M + 20, y + 18, { align: "center" });

  setNavy();
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text(`Overall Risk Rating: ${config.riskScore.riskRating}`, M + 34, y + 10);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  setGray();
  doc.text(`Composite climate risk score: ${config.riskScore.overall}/100 | Data confidence: ${config.riskScore.confidence}%`, M + 34, y + 18);
  doc.text(`Vulnerability Index: ${config.riskScore.vulnerabilityIndex} | Adaptation Capacity: ${config.riskScore.adaptationCapacity}`, M + 34, y + 25);
  y += 36;

  // Key metrics table
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  setNavy();
  doc.text("Key Risk Metrics", M + 6, y);
  y += 6;

  const metrics = [
    ["Physical Risk Score", `${config.riskScore.physicalRisk.score}/100`],
    ["Transition Risk Score", `${config.riskScore.transitionRisk.score}/100`],
    ["ESG Score", `${config.riskScore.esgScore.score}/100`],
    ["Scope 1+2 Emissions", `${((config.formData.emissions.scope1 + config.formData.emissions.scope2) / 1000).toFixed(0)}k tCO₂e`],
    ["Carbon Intensity", `${((config.formData.emissions.scope1 + config.formData.emissions.scope2) / Math.max(1, 50)).toFixed(0)} tCO₂e/$M revenue`],
  ];

  (doc as unknown as { autoTable: (opts: object) => void }).autoTable({
    startY: y,
    head: [["Indicator", "Value"]],
    body: metrics,
    theme: "striped",
    headStyles: { fillColor: BRAND.navy, textColor: [255, 255, 255], fontStyle: "bold" },
    alternateRowStyles: { fillColor: BRAND.bg },
    columnStyles: { 1: { fontStyle: "bold", textColor: BRAND.teal } },
    margin: { left: M + 6, right: M },
  });

  y = ((doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable?.finalY ?? y + 40) + 8;

  // Top risks
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  setNavy();
  doc.text("Top 3 Material Risks", M + 6, y);
  y += 6;

  const topRisks = [
    { rank: "1", risk: "Transition — Carbon Pricing Exposure", score: config.riskScore.transitionRisk.policy, action: "Develop internal carbon price mechanism and carbon budget" },
    { rank: "2", risk: "Physical — Coastal/Flood Asset Exposure", score: config.riskScore.physicalRisk.acute, action: "Commission site-level physical risk assessment for priority assets" },
    { rank: "3", risk: "Transition — Technology Stranded Asset Risk", score: config.riskScore.transitionRisk.technology, action: "Accelerate renewable energy transition; phase out high-carbon assets" },
  ];

  topRisks.forEach((r, i) => {
    const bx = M + 6;
    const by = y + i * 20;
    const fillColor: [number, number, number] = i === 0 ? BRAND.danger : i === 1 ? [224, 123, 58] : BRAND.amber;
    doc.setFillColor(...fillColor);
    doc.roundedRect(bx, by, 6, 16, 1, 1, "F");
    setNavy();
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.text(r.risk, bx + 10, by + 6);
    doc.setFont("helvetica", "normal");
    setGray();
    doc.text(`Score: ${r.score}/100 | Action: ${r.action}`, bx + 10, by + 12);
  });

  y += topRisks.length * 20 + 8;

  addFooter(2);

  // ─── PAGE 3: METHODOLOGY ───
  doc.addPage();
  addHeader("Methodology", "Scoring framework, data sources, and confidence rating");

  y = 46;
  const methodContent = [
    ["Framework Alignment", "This report follows the Task Force on Climate-related Financial Disclosures (TCFD) recommendations, incorporating all four TCFD pillars: Governance, Strategy, Risk Management, and Metrics & Targets."],
    ["IPCC AR6 Scenarios", `Analysis uses IPCC Sixth Assessment Report (AR6) Shared Socioeconomic Pathways (SSPs) and Representative Concentration Pathways (RCPs). Selected scenario: ${config.scenario}°C (${WARMING_SCENARIOS[config.scenario as keyof typeof WARMING_SCENARIOS]?.rcp ?? "RCP 4.5"}).`],
    ["Physical Risk Scoring", "Acute physical risks scored using: heat stress day frequency, flood zone designation, coastal proximity, wildfire exposure, and water stress index. Chronic risks incorporate temperature trend analysis and sea level rise projections."],
    ["Transition Risk Scoring", "Policy risk based on carbon intensity vs. sector benchmark and jurisdictional carbon pricing exposure. Technology risk from fossil fuel dependency and stranded asset analysis. Market risk from consumer transition scenarios."],
    ["ESG Scoring", "Environmental (50%): emissions trajectory, energy mix, carbon intensity. Social (25%): supply chain vulnerability, labor practices. Governance (25%): board oversight, TCFD/CDP disclosure, net zero commitment."],
  ];

  methodContent.forEach(([title, text]) => {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    setTeal();
    doc.text(title, M + 6, y);
    y += 5;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    setNavy();
    const lines = doc.splitTextToSize(text, W - M * 2 - 10) as string[];
    doc.text(lines, M + 6, y);
    y += lines.length * 4.5 + 5;
  });

  // Data sources table
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  setNavy();
  doc.text("Data Sources", M + 6, y);
  y += 4;

  (doc as unknown as { autoTable: (opts: object) => void }).autoTable({
    startY: y,
    head: [["API", "Provider", "Data Type", "Key Required"]],
    body: [
      ["Open-Meteo", "Open-Meteo GmbH", "Historical climate, temperature, precipitation", "No"],
      ["NASA POWER", "NASA Langley", "Solar radiation, wind, temperature, humidity", "No"],
      ["World Bank", "World Bank Group", "Country emissions, GDP, climate indicators", "No"],
      ["OpenAQ", "OpenAQ", "Real-time PM2.5, PM10, NO2, CO, SO2", "No"],
      ["ReliefWeb", "UN OCHA", "Disaster events: floods, storms, droughts", "No"],
      ["REST Countries", "restcountries.com", "Country metadata, coordinates", "No"],
      ["UN SDG API", "United Nations", "Sustainable Development Goal indicators", "No"],
      ["NOAA CDO", "NOAA/NCDC", "Climate observations, station data", "Free token"],
    ],
    theme: "striped",
    headStyles: { fillColor: BRAND.navy, textColor: [255, 255, 255] },
    alternateRowStyles: { fillColor: BRAND.bg },
    margin: { left: M + 6, right: M },
  });

  addFooter(3);

  // ─── PAGE 4: PHYSICAL RISK ───
  doc.addPage();
  addHeader("Physical Risk Assessment", `Acute & Chronic climate hazard exposure · ${config.scenario}°C scenario`);
  y = 46;

  // Acute risks
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  setNavy();
  doc.text("Acute Physical Risks", M + 6, y);
  y += 4;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  setGray();
  doc.text("Extreme weather event exposure — probability and financial impact", M + 6, y);
  y += 8;

  (doc as unknown as { autoTable: (opts: object) => void }).autoTable({
    startY: y,
    head: [["Hazard", "Exposure Level", "Annual Probability", "Financial Impact", "Trend"]],
    body: [
      ["Extreme Heat Events", config.formData.physicalAssets.heatStressDays > 20 ? "HIGH" : config.formData.physicalAssets.heatStressDays > 10 ? "MEDIUM" : "LOW", `${config.formData.physicalAssets.heatStressDays > 15 ? "35-50%" : "15-25%"}`, `${config.riskScore.physicalRisk.acute > 60 ? "5-10% revenue" : "1-3% revenue"}`, "↑ Increasing"],
      ["Flooding / Storm Surge", config.formData.physicalAssets.floodZone ? "HIGH" : config.formData.physicalAssets.coastalProximity ? "MEDIUM" : "LOW", config.formData.physicalAssets.floodZone ? "20-30%" : "5-12%", config.formData.physicalAssets.floodZone ? "8-15% assets" : "1-4% assets", "↑ Increasing"],
      ["Wildfires", config.formData.physicalAssets.wildfireZone ? "HIGH" : "LOW", config.formData.physicalAssets.wildfireZone ? "15-25%" : "2-5%", config.formData.physicalAssets.wildfireZone ? "4-8% assets" : "<1% assets", "↑ Increasing"],
      ["Water Scarcity", config.formData.physicalAssets.waterStressRegion ? "HIGH" : "MEDIUM", `${Math.round(config.formData.physicalAssets.waterStressIndex * 100)}% stress`, `${config.formData.physicalAssets.waterStressRegion ? "3-7% revenue" : "1-2% revenue"}`, "↑ Worsening"],
    ],
    theme: "striped",
    headStyles: { fillColor: BRAND.teal, textColor: [255, 255, 255] },
    alternateRowStyles: { fillColor: BRAND.bg },
    margin: { left: M + 6, right: M },
  });

  y = ((doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable?.finalY ?? y + 50) + 10;

  // Chronic risks
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  setNavy();
  doc.text("Chronic Physical Risks", M + 6, y);
  y += 8;

  (doc as unknown as { autoTable: (opts: object) => void }).autoTable({
    startY: y,
    head: [["Chronic Risk", "2030 Impact", "2040 Impact", "2050 Impact", "Sensitivity"]],
    body: [
      ["Temperature Rise", `+${(parseFloat(config.scenario) * 0.4).toFixed(1)}°C`, `+${(parseFloat(config.scenario) * 0.7).toFixed(1)}°C`, `+${parseFloat(config.scenario).toFixed(1)}°C`, SECTOR_CONFIGS[config.formData.companyProfile.industry].waterStressSensitivity > 0.6 ? "HIGH" : "MEDIUM"],
      ["Sea Level Rise", "+12cm", "+22cm", "+40cm", config.formData.physicalAssets.coastalProximity ? "HIGH" : "LOW"],
      ["Drought Frequency", "+15%", "+28%", "+45%", config.formData.physicalAssets.waterStressRegion ? "HIGH" : "MEDIUM"],
      ["Precipitation Shifts", "±8%", "±14%", "±22%", sector.waterStressSensitivity > 0.7 ? "HIGH" : "MEDIUM"],
    ],
    theme: "striped",
    headStyles: { fillColor: BRAND.navy, textColor: [255, 255, 255] },
    alternateRowStyles: { fillColor: BRAND.bg },
    margin: { left: M + 6, right: M },
  });

  addFooter(4);

  // ─── PAGE 5: TRANSITION RISK ───
  doc.addPage();
  addHeader("Transition Risk Assessment", "Policy, Technology, Market & Reputational risks");
  y = 46;

  // Score bars
  [
    { label: "Policy Risk", score: config.riskScore.transitionRisk.policy },
    { label: "Technology Risk", score: config.riskScore.transitionRisk.technology },
    { label: "Market Risk", score: config.riskScore.transitionRisk.market },
    { label: "Reputation Risk", score: config.riskScore.transitionRisk.reputation },
  ].forEach(({ label, score }) => {
    scoreBar(M + 6, y, score, 120, label);
    y += 12;
  });
  y += 4;

  // Carbon pricing table
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  setNavy();
  doc.text("Carbon Pricing Exposure Analysis", M + 6, y);
  y += 4;

  const totalEmissions = config.formData.emissions.scope1 + config.formData.emissions.scope2;
  (doc as unknown as { autoTable: (opts: object) => void }).autoTable({
    startY: y,
    head: [["Carbon Price", "Annual Carbon Cost", "% of Revenue", "Risk Level"]],
    body: Object.entries(CARBON_PRICE_SCENARIOS).map(([scenario, price]) => {
      const cost = totalEmissions * price;
      const revBase = 50_000_000;
      const pct = ((cost / revBase) * 100).toFixed(1);
      return [
        `$${price}/tCO₂e (${scenario})`,
        `$${(cost / 1e6).toFixed(2)}M`,
        `${pct}%`,
        parseFloat(pct) > 5 ? "CRITICAL" : parseFloat(pct) > 2 ? "HIGH" : parseFloat(pct) > 0.5 ? "MEDIUM" : "LOW",
      ];
    }),
    theme: "striped",
    headStyles: { fillColor: BRAND.teal, textColor: [255, 255, 255] },
    alternateRowStyles: { fillColor: BRAND.bg },
    margin: { left: M + 6, right: M },
  });

  y = ((doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable?.finalY ?? y + 40) + 8;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  setNavy();
  doc.text("Regulatory Landscape Assessment", M + 6, y);
  y += 4;

  (doc as unknown as { autoTable: (opts: object) => void }).autoTable({
    startY: y,
    head: [["Regulation", "Jurisdiction", "Applicability", "Timeline"]],
    body: [
      ["EU CSRD (Corporate Sustainability Reporting)", "European Union", sector.regulatoryExposure > 0.7 ? "HIGH" : "MEDIUM", "2024-2026 phased"],
      ["SEC Climate Disclosure Rules", "United States", "PUBLIC COMPANIES", "2024+"],
      ["IFRS S2 Climate Disclosures", "Global (ISSB)", "VOLUNTARY → MANDATORY", "2025+"],
      ["Carbon Border Adjustment (CBAM)", "EU imports", sector.carbonIntensityBenchmark > 300 ? "HIGH" : "MEDIUM", "2026"],
      ["Science-Based Targets (SBTi)", "Global", "Voluntary", "Ongoing"],
    ],
    theme: "striped",
    headStyles: { fillColor: BRAND.navy, textColor: [255, 255, 255] },
    alternateRowStyles: { fillColor: BRAND.bg },
    margin: { left: M + 6, right: M },
  });

  addFooter(5);

  // ─── PAGE 6: ESG PERFORMANCE ───
  doc.addPage();
  addHeader("ESG Performance Analysis", "Environmental, Social & Governance scoring vs. benchmarks");
  y = 46;

  [
    { label: "Environmental Score", score: config.riskScore.esgScore.environmental },
    { label: "Social Score", score: config.riskScore.esgScore.social },
    { label: "Governance Score", score: config.riskScore.esgScore.governance },
    { label: "Overall ESG", score: config.riskScore.esgScore.score },
  ].forEach(({ label, score }) => {
    scoreBar(M + 6, y, score, 140, label);
    y += 12;
  });
  y += 4;

  (doc as unknown as { autoTable: (opts: object) => void }).autoTable({
    startY: y,
    head: [["ESG Dimension", "Your Score", "Sector Median", "Global Leader", "Gap"]],
    body: [
      ["Environmental", `${config.riskScore.esgScore.environmental}/100`, "55/100", "22/100", `${config.riskScore.esgScore.environmental - 22} pts behind`],
      ["Social", `${config.riskScore.esgScore.social}/100`, "50/100", "20/100", `${config.riskScore.esgScore.social - 20} pts behind`],
      ["Governance", `${config.riskScore.esgScore.governance}/100`, "48/100", "18/100", `${config.riskScore.esgScore.governance - 18} pts behind`],
      ["Composite ESG", `${config.riskScore.esgScore.score}/100`, "51/100", "20/100", `${config.riskScore.esgScore.score - 20} pts behind`],
    ],
    theme: "striped",
    headStyles: { fillColor: BRAND.success, textColor: [255, 255, 255] },
    alternateRowStyles: { fillColor: BRAND.bg },
    margin: { left: M + 6, right: M },
  });

  y = ((doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable?.finalY ?? y + 40) + 10;

  // UN SDG Alignment
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  setNavy();
  doc.text("UN SDG Alignment Matrix", M + 6, y);
  y += 4;

  (doc as unknown as { autoTable: (opts: object) => void }).autoTable({
    startY: y,
    head: [["SDG Goal", "Target", "Company Alignment", "Evidence"]],
    body: [
      ["SDG 7 — Clean Energy", "7.2: Renewable share", config.formData.emissions.renewablePercent > 50 ? "ALIGNED" : "PARTIAL", `${config.formData.emissions.renewablePercent}% renewable`],
      ["SDG 13 — Climate Action", "13.2: GHG targets", config.formData.esgGovernance.netZeroYear ? "PARTIAL" : "NOT SET", config.formData.esgGovernance.netZeroYear ? `Net zero by ${config.formData.esgGovernance.netZeroYear}` : "No target"],
      ["SDG 6 — Clean Water", "6.4: Water efficiency", config.formData.physicalAssets.waterStressIndex < 0.4 ? "ALIGNED" : "AT RISK", `Stress index: ${config.formData.physicalAssets.waterStressIndex}`],
      ["SDG 12 — Responsible Consumption", "12.c: Fossil subsidies", config.formData.emissions.fossilFuelPercent < 50 ? "PARTIAL" : "NOT ALIGNED", `${config.formData.emissions.fossilFuelPercent}% fossil fuel`],
    ],
    theme: "striped",
    headStyles: { fillColor: BRAND.navy, textColor: [255, 255, 255] },
    alternateRowStyles: { fillColor: BRAND.bg },
    margin: { left: M + 6, right: M },
  });

  addFooter(6);

  // ─── PAGE 7: SCENARIO ANALYSIS ───
  doc.addPage();
  addHeader("Scenario Analysis", "1.5°C | 2°C | 3-4°C warming pathway comparison");
  y = 46;

  (doc as unknown as { autoTable: (opts: object) => void }).autoTable({
    startY: y,
    head: [["Impact Category", "1.5°C Path", "2°C Path", "3-4°C Path"]],
    body: [
      ["Physical risk increase by 2050", "+15%", "+28%", "+55%"],
      ["Financial value at risk (% revenue)", "2-5%", "5-12%", "15-30%"],
      ["Carbon cost (current trajectory)", `$${(config.formData.emissions.scope1 * 50 / 1e6).toFixed(1)}M`, `$${(config.formData.emissions.scope1 * 100 / 1e6).toFixed(1)}M`, `$${(config.formData.emissions.scope1 * 200 / 1e6).toFixed(1)}M`],
      ["Stranded asset exposure (% assets)", "5-10%", "15-25%", "30-50%"],
      ["Insurance premium increase", "+20-30%", "+40-60%", "+80-150%"],
      ["Transition cost (CAPEX)", "Moderate", "High", "Very High"],
      ["Supply chain disruption risk", "Low-Medium", "Medium-High", "High-Extreme"],
      ["Adaptation CAPEX required", "1-2% revenue", "3-5% revenue", "8-15% revenue"],
    ],
    theme: "striped",
    headStyles: { fillColor: BRAND.navy, textColor: [255, 255, 255] },
    bodyStyles: { fontSize: 9 },
    columnStyles: {
      1: { textColor: BRAND.success as [number, number, number] },
      2: { textColor: [224, 123, 58] as [number, number, number] },
      3: { textColor: BRAND.danger as [number, number, number] },
    },
    alternateRowStyles: { fillColor: BRAND.bg },
    margin: { left: M + 6, right: M },
  });

  y = ((doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable?.finalY ?? y + 70) + 8;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  setNavy();
  doc.text("Timeline Milestones", M + 6, y);
  y += 6;

  (doc as unknown as { autoTable: (opts: object) => void }).autoTable({
    startY: y,
    head: [["Milestone", "2030", "2040", "2050"]],
    body: [
      ["Required emissions reduction", "-45% vs 2019", "-68% vs 2019", "-100% (net zero)"],
      ["Carbon price projection", "$75-130/tCO₂e", "$130-200/tCO₂e", "$200-250/tCO₂e"],
      ["Paris Agreement review", "NDC update #3", "NDC update #4", "Net zero target year"],
      ["EU CSRD compliance", "Full reporting", "Enhanced disclosure", "Full value chain"],
    ],
    theme: "striped",
    headStyles: { fillColor: BRAND.teal, textColor: [255, 255, 255] },
    alternateRowStyles: { fillColor: BRAND.bg },
    margin: { left: M + 6, right: M },
  });

  addFooter(7);

  // ─── PAGE 8: FINANCIAL MATERIALITY ───
  doc.addPage();
  addHeader("Financial Materiality", "Value at risk, stranded assets & carbon cost trajectory");
  y = 46;

  const totalEmissionsCalc = config.formData.emissions.scope1 + config.formData.emissions.scope2;
  const revBase = 50_000_000;

  (doc as unknown as { autoTable: (opts: object) => void }).autoTable({
    startY: y,
    head: [["Financial Risk Category", "Low Scenario", "Central Scenario", "High Scenario"]],
    body: [
      [
        "Physical damage (% revenue)",
        `${(config.riskScore.physicalRisk.score * 0.05).toFixed(1)}%`,
        `${(config.riskScore.physicalRisk.score * 0.10).toFixed(1)}%`,
        `${(config.riskScore.physicalRisk.score * 0.20).toFixed(1)}%`,
      ],
      [
        "Carbon cost exposure",
        `$${(totalEmissionsCalc * 50 / 1e6).toFixed(2)}M/yr`,
        `$${(totalEmissionsCalc * 100 / 1e6).toFixed(2)}M/yr`,
        `$${(totalEmissionsCalc * 200 / 1e6).toFixed(2)}M/yr`,
      ],
      [
        "Stranded asset write-down",
        `${(config.riskScore.transitionRisk.technology * 0.05).toFixed(1)}% of assets`,
        `${(config.riskScore.transitionRisk.technology * 0.15).toFixed(1)}% of assets`,
        `${(config.riskScore.transitionRisk.technology * 0.30).toFixed(1)}% of assets`,
      ],
      [
        "Insurance premium increase",
        "+10-20%",
        "+30-50%",
        "+70-120%",
      ],
      [
        "Adaptation CAPEX needed",
        `$${(revBase * 0.01 / 1e6).toFixed(1)}M`,
        `$${(revBase * 0.03 / 1e6).toFixed(1)}M`,
        `$${(revBase * 0.08 / 1e6).toFixed(1)}M`,
      ],
    ],
    theme: "striped",
    headStyles: { fillColor: BRAND.navy, textColor: [255, 255, 255] },
    alternateRowStyles: { fillColor: BRAND.bg },
    margin: { left: M + 6, right: M },
  });

  addFooter(8);

  // ─── PAGE 9: RECOMMENDATIONS ───
  doc.addPage();
  addHeader("Recommendations & Action Plan", "Prioritized climate transition roadmap");
  y = 46;

  const recommendations = [
    {
      priority: "HIGH",
      timeframe: "0–2 years",
      actions: [
        "Complete TCFD-aligned climate risk assessment and publish disclosure report",
        "Set science-based emissions targets (SBTi) aligned with 1.5°C pathway",
        "Establish internal carbon price ($50–75/tCO₂e) for investment decision-making",
        "Commission physical site-level risk assessment for priority assets",
      ],
    },
    {
      priority: "MEDIUM",
      timeframe: "2–5 years",
      actions: [
        "Achieve 50%+ renewable electricity through PPAs or on-site generation",
        "Integrate climate risk into supply chain procurement standards",
        "Develop climate adaptation plan for high-risk physical assets",
        "Begin CDP annual disclosure; target B rating or better",
      ],
    },
    {
      priority: "LOW",
      timeframe: "5–10 years",
      actions: [
        "Achieve net zero Scope 1+2 emissions with verified removals",
        "Publish full Scope 3 value chain emissions and reduction pathway",
        "Develop Nature-Based Solutions portfolio for biodiversity credits",
        "Achieve CSRD/ISSB full compliance for comprehensive ESG reporting",
      ],
    },
  ];

  recommendations.forEach(({ priority, timeframe, actions }) => {
    const pColors: Record<string, [number, number, number]> = {
      HIGH: BRAND.danger, MEDIUM: [224, 123, 58], LOW: BRAND.success,
    };
    doc.setFillColor(...(pColors[priority] ?? BRAND.teal));
    doc.roundedRect(M + 6, y, W - M * 2 - 6, 6, 2, 2, "F");
    setWhite();
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.text(`${priority} PRIORITY — ${timeframe}`, M + 12, y + 4.2);
    setNavy();
    y += 9;
    actions.forEach((action) => {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9);
      const lines = doc.splitTextToSize(`• ${action}`, W - M * 2 - 16) as string[];
      doc.text(lines, M + 10, y);
      y += lines.length * 4.5 + 1;
    });
    y += 5;
  });

  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  setNavy();
  doc.text("Disclosure Improvement Suggestions", M + 6, y);
  y += 5;

  [
    "TCFD: Publish annual TCFD-aligned report with scenario analysis",
    "GRI: Adopt GRI Standards 305 (Emissions) and GRI 303 (Water)",
    "CSRD: Prepare for EU Corporate Sustainability Reporting Directive if applicable",
    "CDP: Submit annual CDP Climate Change questionnaire",
    "SBTi: Validate near-term and long-term science-based targets",
  ].forEach((item) => {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    setGray();
    doc.text(`• ${item}`, M + 6, y);
    y += 6;
  });

  addFooter(9);

  // ─── PAGE 10: APPENDIX ───
  doc.addPage();
  addHeader("Appendices", "Raw data, methodology weights, glossary & data sources");
  y = 46;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  setNavy();
  doc.text("Appendix B: Scoring Weights", M + 6, y);
  y += 4;

  (doc as unknown as { autoTable: (opts: object) => void }).autoTable({
    startY: y,
    head: [["Risk Dimension", "Component", "Weight", "Data Source"]],
    body: [
      ["Physical Risk (40%)", "Acute hazards", "45%", "Open-Meteo, NASA POWER"],
      ["Physical Risk (40%)", "Chronic risks", "55%", "Open-Meteo, World Bank"],
      ["Transition Risk (40%)", "Policy risk", "35%", "Sector config, regulatory data"],
      ["Transition Risk (40%)", "Technology risk", "30%", "Asset composition, energy mix"],
      ["Transition Risk (40%)", "Market risk", "20%", "Consumer scenarios"],
      ["Transition Risk (40%)", "Reputation risk", "15%", "Disclosure assessment"],
      ["ESG Score (20%)", "Environmental", "50%", "Emissions data, CDP"],
      ["ESG Score (20%)", "Social", "25%", "Supply chain, labor"],
      ["ESG Score (20%)", "Governance", "25%", "TCFD, CDP, board"],
    ],
    theme: "striped",
    headStyles: { fillColor: BRAND.navy, textColor: [255, 255, 255] },
    alternateRowStyles: { fillColor: BRAND.bg },
    margin: { left: M + 6, right: M },
  });

  y = ((doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable?.finalY ?? y + 60) + 10;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  setNavy();
  doc.text("Appendix C: Climate Finance Glossary", M + 6, y);
  y += 4;

  const glossary = [
    ["TCFD", "Task Force on Climate-related Financial Disclosures"],
    ["IPCC AR6", "Intergovernmental Panel on Climate Change 6th Assessment Report"],
    ["RCP", "Representative Concentration Pathway — greenhouse gas concentration trajectory"],
    ["SBTi", "Science Based Targets initiative — validates corporate emission reduction targets"],
    ["Physical Risk", "Direct risks from climate hazards (floods, heat, storms, drought)"],
    ["Transition Risk", "Risks from shift to low-carbon economy (policy, technology, market)"],
    ["Carbon Intensity", "GHG emissions per unit of economic output (tCO₂e per $M revenue)"],
    ["Stranded Asset", "Asset that has suffered unexpected write-down due to climate transition"],
    ["CSRD", "EU Corporate Sustainability Reporting Directive"],
    ["Paris Agreement", "2015 international treaty limiting warming to 1.5–2°C above pre-industrial"],
  ];

  glossary.forEach(([term, def]) => {
    if (y > H - 25) {
      doc.addPage();
      addHeader("Appendices (continued)", "Glossary & Data Sources");
      y = 46;
    }
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    setTeal();
    doc.text(term + ":", M + 6, y);
    doc.setFont("helvetica", "normal");
    setNavy();
    const lines = doc.splitTextToSize(def, W - M * 2 - 50) as string[];
    doc.text(lines, M + 40, y);
    y += 7;
  });

  addFooter(doc.getNumberOfPages());

  doc.save(`Climactix_Risk_Report_${config.companyName.replace(/\s+/g, "_")}_${new Date().toISOString().split("T")[0]}.pdf`);
}
